name: Get Rank Value

on:
  push:
    branches:
      - main

jobs:
  extract-rank:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          npm install puppeteer

      - name: Get Rank value
        run: |
          node -e '
          const puppeteer = require("puppeteer");

          (async () => {
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
            await page.goto("https://leetcode.com/imacemarx", { waitUntil: "networkidle0" });
            const rankElement = await page.$(".ttext-label-1.dark\\:text-dark-label-1.font-medium");
            const rankValue = await rankElement.evaluate((el) => el.innerText);
            console.log("Rank:", rankValue);
            await browser.close();
          })();
          '
