name: Get Rank Value

on:
  push:
    branches:
      - main

jobs:
  extract-rank:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          npm install puppeteer

      - name: Get Rank value
        run: |
          node -e '
          const fs = require("fs");
          const puppeteer = require("puppeteer");

          (async () => {
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
            await page.goto("https://leetcode.com/imacemarx", { waitUntil: "networkidle0" });
            const rankElement = await page.$(".ttext-label-1.dark\\:text-dark-label-1.font-medium");
            const rankValue = await rankElement.evaluate((el) => el.innerText);
            console.log("Rank:", rankValue);

            // Format the current date and time
            const currentDate = new Date().toISOString().replace(/[-:.TZ]/g, "");
            const formattedDate = `${currentDate.substr(0, 8)}T${currentDate.substr(8)}`;

            // Read existing file contents
            let existingContent = "";
            try {
              existingContent = fs.readFileSync("myrank", "utf8");
            } catch (error) {
              console.log("No existing file found. Creating new file.");
              fs.writeFileSync("myrank", "");
            }

            // Update file with new rank value and current date
            const updatedContent = `${formattedDate}:${rankValue}\n${existingContent}`;
            fs.writeFileSync("myrank", updatedContent);

            await browser.close();
          })();
          '

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add myrank
          git commit -m "Update rank value"
          git push
